<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Authors>Microsoft.Marketplace</Authors>
		<Company>Microsoft</Company>
		<Product>Marketplace.SaaS.Accelerator</Product>
		<AssemblyName>DataAccess</AssemblyName>
		<RootNamespace>Marketplace.SaaS.Accelerator.DataAccess</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Context\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.21.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>