#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app


FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . .
WORKDIR "/src/CustomerSite"
RUN dotnet build "CustomerSite.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CustomerSite.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:443
EXPOSE 443

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CustomerSite.dll"]