# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build, Deploy and Test on PR

on:
  pull_request:
    branches: [ "main" ]
    
env:  
  CUSTOMER_PROJECT: './src/CustomerSite/CustomerSite.csproj'
  PUBLISHER_PROJECT: './src/AdminSite/AdminSite.csproj'
  SERVICES_TEST_PROJECT: './src/Services.Test/Services.Test.csproj'
  UI_TEST_PROJECT: './src/UI.Test/UI.Test.csproj'
  CUSTOMER_AZURE_WEBAPP_PACKAGE_PATH: './src/Marketplace.SaaS.Accelerator.CustomerSite/Publish/Customer'
  PUBLISHER_AZURE_WEBAPP_PACKAGE_PATH: './src/Marketplace.SaaS.Accelerator.AdminSite/Publish/Admin'
  DOTNET_CORE_VERSION: '6.0.x'
  
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    # Run dotnet build and publish
    - name: Build app
      run: |
        dotnet build ${{ env.PUBLISHER_PROJECT }} --configuration Release
        dotnet publish ${{ env.PUBLISHER_PROJECT }} --configuration Release --no-build --output ${{ env.PUBLISHER_AZURE_WEBAPP_PACKAGE_PATH }}

    # Deploy to Azure Web app
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_PUBLISHER_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISHER_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.PUBLISHER_AZURE_WEBAPP_PACKAGE_PATH }}
        
    # Build/Publish Customer Site
    - name: Build/Test Customer app
      run: |
        dotnet build ${{ env.CUSTOMER_PROJECT }} --configuration Release
        dotnet test ${{ env.SERVICES_TEST_PROJECT }}
        dotnet publish ${{ env.CUSTOMER_PROJECT }} --configuration Release --no-build --output ${{ env.CUSTOMER_AZURE_WEBAPP_PACKAGE_PATH }}
      
    # Build/Publish Admin Site
    - name: Build/Test Admin app
      run: |
        dotnet build ${{ env.PUBLISHER_PROJECT }} --configuration Release
        dotnet test ${{ env.SERVICES_TEST_PROJECT }}
        dotnet publish ${{ env.PUBLISHER_PROJECT }} --configuration Release --no-build --output ${{ env.PUBLISHER_AZURE_WEBAPP_PACKAGE_PATH }}

        
    # Deploy Customer Site
    - name: Deploy Customer App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_CUSTOMER_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_CUSTOMER_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.CUSTOMER_AZURE_WEBAPP_PACKAGE_PATH }}
             
        
    # Deploy Admin Site
    - name: Deploy Admin App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_PUBLISHER_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISHER_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.PUBLISHER_AZURE_WEBAPP_PACKAGE_PATH }}
    
    # Run UI Tests    
    - name: Run UI Test
      working-directory: ./src
      run: AppSetting__adminAppURL=secrets.TEST_ADMIN_APPURL dotnet test ${{ env.UI_TEST_PROJECT }}
